name: Docker CI/CD pipeline

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

  jobs: 
    build-test-deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true

      - name: Build Docker image
        run: |
          docker build -t my-html-app:latest .
          echo "Docker build check"
      - name: Test Docker container
        run: |
          docker run -d -p 8080:80 --name test-container my-html-app:latest

          sleep 5

          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)

          if [ $response -eq 200 ]; then
            echo "Container passed"
          else
            echo "Container test failed $response"
            
            docker stop test-container
            docker rm test-container
            exit 1
          fi 

          docker stop test-container
          docker rm test-container

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag my-html-app:latest ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
          docker tag my-html-app:latest ${{ secrets.DOCKER_USERNAME }}/my-html-app:${{ github.sha }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:${{ github.sha }}
          echo " Image pushed to Docker Hub"
        continue-on-error: true
      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        run: |
          echo " Deploy Done "
          echo " App is ready"
          echo "You can run docker run -d -p 80:80 my-html-app:latest"

      

